### ISSUE TITLE
Periodicity of ATAC peak widths

### ISSUE THREAD

**Issue by pgugger** [jsh58/Genrich#27]
Hi John and others, In comparing ATAC-Seq peaks produced by Genrich and MACS2 in both paired-end and single-end modes, I plotted histograms of the peak widths and observed some striking difference. The Genrich results are multimodal and show a clear periodicity that roughly mirrors the periodicity in fragment sizes in the input BAM files. However, the MACS2 results do not show such a pattern, though there is perhaps a trace that is slightly offset in the MACS2 PE results. Is the periodicity of peak widths expected, or what do you make of the differences in these results?

Here are some plots (same scale) demonstrating what I mean:
![Genrich](https://user-images.githubusercontent.com/9573617/62150966-43614a00-b2cd-11e9-8e55-9238d8901315.png)
![MAC2_PE](https://user-images.githubusercontent.com/9573617/62150965-43614a00-b2cd-11e9-9116-7368718df100.png)
![MACS2_SE](https://user-images.githubusercontent.com/9573617/62150964-43614a00-b2cd-11e9-990e-a9665e0e1bef.png)

I used commonly chosen arguments for each analysis and removed mm10 blacklisted regions. There are similar numbers of peak regions (85-87k), regardless of peak caller. The peak call sets have about  87% overlap when running `bedtools intersect` or `bedtools subtract`.

Thanks for your help.

Paul

**Comment by jsh58** [comment]
Paul,

Interesting result, and thanks for including the graphs.

This is probably due to the differences in alignment interpretation.  I will refer you to the paragraph after Figure 4 [here](https://github.com/jsh58/ATAC-seq2#another-peak-caller--why).  Did you adjust the parameters of macs2 in single-end mode, to be more ATAC-seq-ish?

John Gaspar

**Comment by pgugger** [comment]
Thanks. Yes, I used something like this for MACS2 SE:
```
MACS2 callpeak -t all.bam --nomodel --shift -100 --extsize 200 --format BAM -g mm10
```

**Comment by jsh58** [comment]
Here are some direct differences between Genrich and macs2 in single-end mode:
* With the command you gave above, macs2 interprets intervals of 200bp (`--extsize 200`).  Genrich uses a [default of 100bp](https://github.com/jsh58/Genrich#atacseq) (`-d`) in ATAC-seq mode.
* With macs2 in single-end mode, the maximum gap between significant regions to join them into a single peak is the average length of the first 10 reads in the BAM.  (Yes, that is nonsensical, but [my edited version of macs2](https://github.com/jsh58/MACS) has a `--max-gap` parameter that can be adjusted.)  Genrich uses a [default of 100bp](https://github.com/jsh58/Genrich#peakcalling) (`-g`).
* With macs2 in single-end mode, the minimum length of a peak is the fragment length (i.e. 200bp, with `--extsize 200`).  Genrich uses AUC peak-calling, and the minimum length is 0bp by default (`-l`)

**Comment by Maarten-vd-Sande** [comment]
I had a similar 'issue' recently. When checking the *pileup* of genrich I noticed clear spacing which I did not see for MACS2. However I realized this was explained by the extsize/-d option. The longer you extend your fragments, the smaller the wavy effects get.

**MACS2** with --extsize 200
![image](https://user-images.githubusercontent.com/15323399/63174237-d6c2ab00-c041-11e9-9401-76655bcc7530.png)
**MACS2** with --extsize 100
![image](https://user-images.githubusercontent.com/15323399/63174198-c14d8100-c041-11e9-88fa-8dc2574c2013.png)

**Genrich** with -d 200
![image](https://user-images.githubusercontent.com/15323399/63174600-944d9e00-c042-11e9-9836-8f8d71a7dd3c.png)

**Genrich** with -d 100
![image](https://user-images.githubusercontent.com/15323399/63174626-a3cce700-c042-11e9-8ab1-b2c547827b2a.png)

I expect that the periodicity you see is caused by the extension length, since shorter fragments clearly show the nucleosome pattern, and thus the peaks called from these patterns are generally *n* nucleosomes long.

**Comment by jsh58** [comment]
@Maarten-vd-Sande, thanks for the images.  The pileups show the effect of varying `--extsize`/`-d` most directly.  They also illustrate another key difference between Genrich and macs2 in single-end mode (which [I've stated before](https://github.com/jsh58/ATAC-seq2#another-peak-caller--why), but it bears repeating):

> in the default (`BAM`) mode [of macs2] ... with paired-end reads, most of the alignments are automatically discarded (half of the properly paired alignments and *all* of the unpaired alignments; secondary alignments are *never* considered).

Going from pileups to peaks adds another layer of complexity, and we must consider those differences (explained [above](https://github.com/jsh58/Genrich/issues/27#issuecomment-520512289)) as well.  For example, the fact that macs2 has a hard cutoff for minimum peak length, and Genrich does not, is clearly seen in the original graphs from @pgugger.
