### ISSUE TITLE
Minimum AUC settings for different number of reads

### ISSUE THREAD

**Issue by ghost** [jsh58/Genrich#63]
Great tool! However, contrary to some other popular peak callers I have been using, Genrich seems to almost always call more peaks in datasets with lower number of reads. I read one of the closed issues here talking about a similar problem, and understood that this phenomenon is caused by decreasing background reads.

Are there some kind of minimum AUC settings for certain ranges of number of reads you can recommend me? Or maybe a recommended minimum number of reads for Genrich? I am working on a automated pipeline, so I am thinking to adjust the minimum AUC setting when running Genrich according to the number of mapped reads in the BAM file, to somewhat prevent Genrich from calling too many insignificant peaks. Do you think it is possible?

Thank you so much!

**Comment by jsh58** [comment]
Thanks for the question.  The closed issue you referred to must be #33.

I cannot recommend any specific settings that you are requesting.  I will recommend that you may want to adjust the minimum AUC based on the `Background pileup value` that is reported by Genrich in verbose mode, rather than the number of reads.
